### ISSUE TITLE
Error for v1.8.0 with libmcfgthread-1.dll

### ISSUE THREAD

**Issue by rayman3003** [FelixdelasPozas/OGG-Extractor#10]
After installing the newly released version of **1.8.0**, the app can't be opened.

When I try to execute the "OGGExtractor.exe", it shows the following error, & refuse to open.

**libmcfgthread-1.dll**

![2023-08-21 11_15_18-Window](https://github.com/FelixdelasPozas/OGG-Extractor/assets/17022701/58fd2797-c271-47aa-9e84-a20553042f8d)

Note: The previous version (1.7.0) can be opened without problem.

**Comment by FelixdelasPozas** [comment]
Hi @rayman3003, thanks for the warning! I've updated the release binaries including the missing dll, please try the [updated release](https://github.com/FelixdelasPozas/OGG-Extractor/releases/tag/1.8.0) and tell me if it works.

I've recently updated the compiler to GCC version 13 and Qt didn't identify that dll as a dependency when doing the release.

Regards,
Félix.

**Comment by rayman3003** [comment]
Now it works.😄

Thank u very much 🤝

**Comment by FelixdelasPozas** [comment]
Great!

**Comment by ghost** [comment]
Seems like the error is back in 1.9.0 (1.8.0 works). Possible regression?

**Comment by FelixdelasPozas** [comment]
Hi @interruptinuse.

I'll add the missing dll. Just for curiosity, what OS are you using? (Because the user that tried it seems to have no problem with it. Maybe you use Windows 7?)

Edit: Updated the release binary with the missing dll. Thanks for reporting it!

**Comment by ghost** [comment]
I'm using Windows 10, Build 19045.

From a cursory glance, it might be the symptom of the following issue: if installing to the directory with the previous version of OGGExtractor, the installer doesn't seem to delete existing files (or `libmcfgthread-1.dll` specifically, at least). In other words, it works if installing 1.8.0 first, then installing 1.9.0 (which doesn't have the DLL, but keeps the DLL from 1.8.0).

**Comment by FelixdelasPozas** [comment]
Ahhh, it just didn't occur to me that that could be the case. The Qt dependencies app doesn't seem to include that dll (I use Win11) and I thought it might be an OS-related thing.

Thanks!
