### ISSUE TITLE
Voice line cut short

### ISSUE THREAD

**Issue by HKanson1234** [FelixdelasPozas/OGG-Extractor#11]
I have some issue on some voice line getting cut short at the end of some ogg files. I extracted ogg files from Far Cry 3\data_win32\worlds\multicommon\multicommon_english.dat on Far Cry 3, suppose the voice below should be "Don't worry I will get to you next". However, the "Next" is partially cut short
00090_multicommon_english.dat_001206628-001219511_(000012883)

A few more examples that have the same issue:
00094_multicommon_english.dat_001258720-001274073_(000015353)
00097_multicommon_english.dat_001313280-001329920_(000016640)

Some ogg had no waveform:
00098_multicommon_english.dat_001330716-001336566_(000005850)

Any idea what cause those problems?

**Comment by FelixdelasPozas** [comment]
Hello @HKanson1234 .

I don't have access to the game, so I can't say. I never had any problem like that but I don't usually extract dialogue, I'm just interested in the music. Are you using the latest version of the program? 1.8.0?
I'll look at the program in the weekend to see if there is a bug writing the trailing bytes of the ogg files.

Regards, 
Félix.

**Comment by HKanson1234** [comment]
Hi @FelixdelasPozas. 

Thanks for the reply, and yes, I'm using 1.8.0 OGG-Extractor. 

Do u need the multicommon_english.dat for test? Btw I used cli to extract the files since gui stop responding at 98%, using cli one will not encounter that problem. 

<img width="398" alt="image" src="https://github.com/FelixdelasPozas/OGG-Extractor/assets/112676843/056ad256-6864-4137-b535-95a64e47ce19">

Let me know if you need more info, thanks.

Regards,
Anson

**Comment by FelixdelasPozas** [comment]
Hi @HKanson1234 .

Tomorrow I'll release a new version that will solve both the problem with the GUI version (the Qt lib can't handle properly that amount of files in the table widget) and the sound clipping problem (that apparently only happens with very short files). 

Thanks for pointing out the problems. I hope the next release will allow you to browse and extract the files without problems. 

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @HKanson1234.

I just released version [1.9.0](https://github.com/FelixdelasPozas/OGG-Extractor/releases/tag/1.9.0) that I think will solve both your problems. 

The UI version should handle now containers with thousands of sound files and present them in "pages" of 1000 ogg files each. 
I recommend using the GUI version as you can rename the output files by double-clicking on the name, you can listen before extracting and select/deselect the ones you want. 

The problem with the audio files being cut short should be fixed now too. 

I'll wait for you to confirm that the problems have been fixed to close this issue. 

Regards, 
Félix.

**Comment by HKanson1234** [comment]
Hi @FelixdelasPozas,

I have tested around 1k files and looks perfect to me, I am closing the issue. Appreciated your time and effort.😊

Regards,
Anson
