### ISSUE TITLE
OGG Extractor no longer can extract unreal games

### ISSUE THREAD

**Issue by rayman3003** [FelixdelasPozas/OGG-Extractor#6]
I used to use OGG Extractor for extracting Oggs from unreal engine games. But the new games that made by newer version(s) of unreal engine, can't be extracted by OGG Extractor anymore.

I think OGG Extractor needs to get updated to be compatible with new version(s) of Unreal Engine.

**Comment by FelixdelasPozas** [comment]
While **OGG Extractor** works with some Unreal Engine games (I've only used with "Thief: Deadly Shadows", that's Unreal Engine 3) it's not intended to work will all Unreal Engine games. As stated in the [readme](https://github.com/FelixdelasPozas/OGG-Extractor/blob/master/readme.md) it scans for OGG headers and thus it will work with unencripted and uncompressed OGG files. But nothing more complicated, it's not intended to process complex containers or to bypass any protection techniques. 
For games that uses other formats for audio, or uses encryption I recommend specialized tools like [UEViewer](https://github.com/gildor2/UEViewer). Look if the game you want is on the [compatibility list](https://www.gildor.org/projects/umodel/compat). 
Good luck!

**Comment by rayman3003** [comment]
> 
> 
> While **OGG Extractor** works with some Unreal Engine games (I've only used with "Thief: Deadly Shadows", that's Unreal Engine 3) it's not intended to work will all Unreal Engine games. As stated in the [readme](https://github.com/FelixdelasPozas/OGG-Extractor/blob/master/readme.md) it scans for OGG headers and thus it will work with unencripted and uncompressed OGG files. But nothing more complicated, it's not intended to process complex containers or to bypass any protection techniques.
> For games that uses other formats for audio, or uses encryption I recommend specialized tools like [UEViewer](https://github.com/gildor2/UEViewer). Look if the game you want is on the [compatibility list](https://www.gildor.org/projects/umodel/compat).
> Good luck!

OK; Thank u for suggesting another tool for this purpose.

But I always used OGG Extractor for extracting OGG from unreal games, And hoped that it could be updated to support recent unreal engine 4.x games.

R u saying that u don't have any interest in updating OGG Extractor, after about 2 years?

**Comment by FelixdelasPozas** [comment]
Sadly that's outside the scope of the tool. **OGG Extractor** is agnostic when it comes to game engines as you can see in the (brief) list of games i've used it for (Hitman games use the _Glacier Engine_, Talos Principle uses the _Serious Engine 4_, Fez uses a custom C# engine I think, etc...). Unreal Engine games are not specially supported, some just happen to use OGG files and others do not. My program only searchs big files for OGG signatures and extracts the associated audio files if found.

Supporting Unreal Engine games specially will require handling of [PAK containers](https://docs.unrealengine.com/en-US/Engine/Basics/Projects/Packaging/index.html#creatingpackages) and apparently [AES encription](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) for versions 4.22 and up of the engine.  As you can see that is another project on its own, one focused on Unreal Engine containers and its formats. **OGG Extractor** is not intended for that, sorry.

So if you want to extract files from a modern game you'll have to rely on tools focused on extracting files from PAK containers as the one I told you before (including Epic Games own UnrealPak.exe used to create them in the first place apparently). But I've never used them as I don't own any Unreal Engine 4.x game.  I can't help you on that. 

Regards,
Félix.

**Comment by rayman3003** [comment]
OK, Thank u for your time. I will use those tools from now on.
