### ISSUE TITLE
CLI functionality

### ISSUE THREAD

**Issue by sparr** [FelixdelasPozas/OGG-Extractor#8]
I would like to be able to run OGG-Extractor without a GUI, just specifying a target file and some options at the command line and getting the extracted files.

I am interested in working on implementation if this idea is welcome. Seeking feedback and input here before I get started.

**Comment by FelixdelasPozas** [comment]
Hello @sparr .

That should be easy to do. Just give me a day or two to implement it. Either making a CLI executable or probably invoking the application with a **-no-gui** command line option. 
Parameters to implement:
- output directory for the extracted files (optional, will use the current dir if not specified)
- minimum file size for extracted files (optional, 0 if not specified)
- minimum length in seconds for the extracted files (optional, 0 if not specified)
- a file or files to scan (non optional, at least one)

Right now I don't think anything else is needed, but if you thing another one could be useful tell me.

Regards,
Félix.

Edited: Creating a mixed console/app application is a bit of a hassle, it can be done but some error messages Qt will use a dialog. Better to make then a CLI executable. Should be easy.

**Comment by sparr** [comment]
Additional feature requests, that are not necessary for an initial version of this feature and could be their own issues for later implementation:
* option to output info about the OGG files in a machine readable format, but not actually extract them to disk
* option to specify which files to extract by number/range (e.g. `--specific-files 1,3,6-9`)

**Comment by FelixdelasPozas** [comment]
That seems oddly specific. Do you plan to integrate it as part of another program? Because adding the number/range requires "prior knowledge" about the contents of a file you've not yet scanned and I'll have to check that the numbers and ranges "match" with the contents (as you can try extract a number bigger than the number of OGG files in the "container" and then the application should show an error message for that).

The idea of a cli version doesn't seem bad, because you might want to process all files in bulk in a script instead of using the UI version (that also can do it if you select and add all files as "containers to scan") but the UI version let's you hear the found files before extracting them so you can "unselect" the ones you don't want.

**Comment by sparr** [comment]
I would be calling it from https://github.com/sparr/vgm-extractor which might have some prior knowledge about the contents of the file, or might ask for one ogg at a time so that additional filtering can be applied before they all get extracted and use up a lot of unnecessary space.

**Comment by FelixdelasPozas** [comment]
@sparr Well, that makes sense then. I hope you credit this project in your readme.md. :smiley: 

> option to output info about the OGG files in a machine readable format, but not actually extract them to disk

I've already implemented this, the information will be dumped in a CSV file, easy to read.

> option to specify which files to extract by number/range (e.g. --specific-files 1,3,6-9)

I'll finish this tomorrow, will be a flag "-r" with the comma separated positions and ranges separated with "-". 

The CLI version doesn't need Qt, so should world _standalone_ as it's just C++, but i haven't tested it yet. I'll update the readme.md file tomorrow with the description on how to call the CLI version.

**Comment by FelixdelasPozas** [comment]
@sparr Just released [version 1.8.0](https://github.com/FelixdelasPozas/OGG-Extractor/releases/tag/1.8.0) with the cli tool (description of the options in the readme.md).
 I've tested it and seems to work fine. If you have any problem with it, let me know opening another issue, I'll close this one in a day if no other problem is reported.

Regards, 
Félix.
